language: python
python:
  - "2.7"
env:
  - DJANGO=1.6
install:
    - pip install -q Django==$DJANGO django-mptt django-meta coveralls --use-mirrors
script:
    - coverage run --source=page run_tests.py
after_success:
    - coveralls
